### ISSUE TITLE
Thumbnail maps not showing background

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#257] opened 2016-07-18 23:54 UTC
The thumbnail maps aren't showing the background, just gray with a question mark. The task squares seem to show up fine.

<img width="846" alt="screen shot 2016-07-18 at 4 53 04 pm" src="https://cloud.githubusercontent.com/assets/5025092/16934106/394e03ba-4d08-11e6-8b9b-d7f3f7cc9b46.png">

**Comment by danbjoseph** [comment] 2016-07-19 00:51
Maybe we hit our Mapbox account limit on views?

**Comment by dalekunce** [comment] 2016-07-19 05:42
confirmed that its not account limits.

@kamicut you have any ideas, I tried swapping out the token and nothing seemed to really change.

**Comment by DylanMoriarty** [comment] 2016-07-19 16:56
Strange that it dropped like that. Bug is with the token and map, the site's currently using mb light, not one from the Redcross.

Updating the token to their public one seems to have fixed it for me locally. 

[PR up here](https://github.com/MissingMaps/partners/pull/32). Should be reviewed before merged.

**Comment by DylanMoriarty** [comment] 2016-07-20 17:36
@dalekunce before you do merge, it would be good to swap out the token (mb's default) with one from the RC account. I'm guessing the reason it didn't work before was because of the extra "+" we originally had to help concatenate a longer string.

If you replace the token here with the RC token it should work. Ping me if it still doesn't for some reason.
https://github.com/MissingMaps/partners/pull/32/commits/d6aca3f7bec2bc721581dc8cb0f99b888a3ca1a9

**Comment by aawiseman** [comment] 2016-07-29 21:14
Looks like it's working now?

**Closed** 2016-09-26 20:08 UTC
