### ISSUE TITLE
site translation/localization

### ISSUE THREAD

**Issue by abenrob** [MissingMaps/missingmaps.github.io#45] opened 2015-10-28 10:03 UTC
Realising this is a big topic; we should brainstorm on the approach here.

Thoughts:
- translation is pretty easy. you need lookups for everything, but once in place it works well.
- localization is harder (displaying times/dates/etc in the correct *format* for the end user. ie 22 AUG means nothing in France...) should be able to use Date.prototype.toLocaleDateString()
- We'd need to identify folks to provide translated copy. Pretty sure we can find FR folks pretty easily, but we'd need to id the translatable components beforehand.

**Comment by abenrob** [comment] 2015-10-28 13:39
Date.prototype.toLocaleDateString() not supported in safari. Can use [moment](http://momentjs.com/)

**Comment by dalekunce** [comment] 2015-10-28 13:46
@abenrob I love the localization. The site itself now is pretty dumb html/css with a tiny bit of javascript (d3). One of our goals is to jekyllfy the whole site but we are waiting on a current project to introduce a new redesign.

**Comment by ThomasG77** [comment] 2015-10-28 14:16
I've started to make the French translation based on the various lurking index.html in the project. I only need to complete the index-fr.html (duplicated version of each index.html) translation in mapathons/index-fr.html. I was thinking about adding a language menu to switch, keeping in first the not really maintainable HTML (for translation)
https://github.com/ThomasG77/missingmaps.github.io

Can we also have the source of the various PDF from https://github.com/MissingMaps/missingmaps.github.io/tree/master/docs? Thanks for your feedback

**Comment by abenrob** [comment] 2015-10-28 14:40
Sounds like we should wait on the redesign? @dalekunce do you know when this might be coming online?

**Comment by dalekunce** [comment] 2015-10-28 14:47
@abenrob not for a couple months. I think following @ThomasG77 workflow will be hugely beneficial as the main text of the site won't change just where it is on the page.

**Comment by ThomasG77** [comment] 2015-10-28 15:04
Ok it seems Ok for the website.

Any input on PDF part? Do I have to do some reverse engineering on the PDF or can we have somewhere the original docs before the PDF transformation?

**Comment by dalekunce** [comment] 2015-10-28 15:51
@ThomasG77 we can share the original docs for the PDFs. These are either InDesign or Illustrator however.

**Comment by ThomasG77** [comment] 2015-10-28 17:30
@dalekunce Can you export them to *.eps and *.svg whenever it's possible? I will reproduce these documents with equivalent Open Source Software (Scribus for InDesign and Inkscape for Illustrator) so they can be editable by anyone on any platforms.

**Comment by leonmvd** [comment] 2016-01-13 18:13
I can translate everything to Dutch and make a start with the German version

**Comment by dalekunce** [comment] 2016-01-14 01:38
@leonmvd thanks for the offer. I would love to see  some translations for the site however we are very close to rolling out a completely new site. If you wait a month there will be tons of new updated content.

**Comment by leonmvd** [comment] 2016-02-25 16:44
Since the site is online now, let's start! Do we need transifex for this or directly in the website?

**Comment by dalekunce** [comment] 2016-02-25 16:46
Great question, let's do a little research first. HOT uses transifex but I'm unfamiliar with it.

**Comment by leonmvd** [comment] 2016-02-25 16:57
For translating it's a nice tool, but I don't know anything about the integration of the translated parts into the website.

**Comment by abenrob** [comment] 2016-02-25 17:02
For [Maptime-Alpes](http://maptime-alpes.com/) I just used a [yml file](https://github.com/MaptimeAlpes/MaptimeAlpes.github.io/blob/develop/_data/locales.yml) to define lookups by locale, and for localization, I used [this plugin](https://github.com/MaptimeAlpes/MaptimeAlpes.github.io/blob/develop/_plugins/i18n_filter.rb), and some pre-made [localization files](https://github.com/MaptimeAlpes/MaptimeAlpes.github.io/tree/develop/_locales)

**Comment by abenrob** [comment] 2016-02-25 17:03
Not familiar with transifex, but the site is pretty basic, so supplying a template yml to translators wouldn't be too hard... (IMO)

**Comment by abenrob** [comment] 2016-02-25 17:08
FYI https://github.com/maptime/maptime-admin/issues/128 All the same questions...

**Comment by dalekunce** [comment] 2016-02-25 17:11
@abenrob @leonmvd I like the yml file option. Can one of you do a PR with a translation to language as a test.

**Comment by abenrob** [comment] 2016-02-25 17:13
I'll make a run at it later tonight.

**Comment by leonmvd** [comment] 2016-02-25 17:19
I can translate the basics to Dutch, German and make a start with French. Will check with some colleagues if they can help out with the texts later

**Comment by abenrob** [comment] 2016-02-25 20:42
General note that landing page has an english language _image_ on it. Will need to be remade for each language or redesigned to support html/svg text. Can it be svg? We can use jekyll on svgs, I believe... Also doc will need translations...

**Comment by abenrob** [comment] 2016-02-25 20:44
Oh wait - it IS and svg... coolio.

**Comment by dalekunce** [comment] 2016-02-25 22:32
@abenrob all images should be svg. It you run into any issues let us know

**Comment by abenrob** [comment] 2016-02-25 22:33
Text has been converted to polygons, so no go there...

**Comment by abenrob** [comment] 2016-02-26 17:18
I have a functioning, localized landing page working well - though not all translated. I'll do up the other pages later tonight and send a PR. At that point we can start getting translation work done by folks

**Comment by abenrob** [comment] 2016-02-26 17:19
Getting the how it works svg with text instead of polys would be a good thing as well, so I can test jekyll template with svg.

**Comment by dalekunce** [comment] 2016-03-03 16:14
merged @abenrob latest commit into the localization branch. Next steps are: 

- [ ] Update Travis build script 
- [ ] update events in merge
- [ ] merging @pedrito1414 PRs into localization branch #131 #130 #129 
- [ ] @DylanMoriarty noticed some CSS fixes that need to happen

cc @DylanMoriarty

**Comment by DylanMoriarty** [comment] 2016-03-03 16:37
@dalekunce @abenrob's latest commits to the Localization branch grab the bugs I'd reported earlier. :+1:

**Comment by abenrob** [comment] 2016-03-03 16:39
I'm about 60% through the fr translation as well. When I finish (and the list above), we should review and push to publish

**Comment by dalekunce** [comment] 2016-03-25 11:46
closed by #148 

Great work everyone.

**Closed** 2016-03-25 11:46 UTC
Labels: enhancement
