### ISSUE TITLE
Stats not catching all my edits (maybe due to case sensitivity?)

### ISSUE THREAD

**Issue by aawiseman** [MissingMaps/missingmaps.github.io#240] opened 2016-07-08 18:50 UTC
I think @dalekunce might be on this one but just in case -- for yesterday's event the Leaderboard site says I did 4 buildings, but I definitely did a lot more. Overpass shows around 60 http://overpass-turbo.eu/s/hd2

It might be related to using #WHMapathon instead of #whmapathon or maybe #missingmaps versus #MissingMaps but I'm not sure. I think in any case it should be case-insensitive.

**Comment by kamicut** [comment] 2016-07-11 13:19
@aawiseman it should be case-insensitive, I'll check to see if we had an issue with the server.

**Comment by aawiseman** [comment] 2016-07-11 16:38
@kamicut thanks. It was the #whmapathon event

**Comment by smit1678** [comment] 2016-07-12 16:14
@kamicut @aawiseman One guess is that part of the problem is overpass and so the system may be dropping edits. I've seen that it's been going offline frequently over the last week.

**Comment by aawiseman** [comment] 2016-07-12 22:14
@smit1678 ah. Does the Missing Maps site use Overpass too?

**Comment by dalekunce** [comment] 2016-07-13 00:32
Overpass is used to get the data to do all the calculations. Now might be the time to make the switch to https://osmlab.github.io/osm-qa-tiles/

**Comment by kamicut** [comment] 2016-07-13 14:27
@dalekunce while we could possibly use the QA tiles to backfill stats for the previous day, we use Overpass to get minutely and real-time updates for the leaderboards. As of yet, there's no other service that can provide dereferenced geometries in real-time. One possible solution would be to stand up an Overpass mirror, or find a mirror that is not heavily used.

**Comment by aawiseman** [comment] 2016-08-05 20:10
Looks like this is still happening, here's some people who did edits with all the hashtags but weren't counted. Does it depend on the order of the hashtags? Like #missingmaps has to be first?

http://www.openstreetmap.org/user/Lisette%20R-Z/history#map=16/18.3708/-88.4046
http://www.openstreetmap.org/user/CY%20Rashid/history#map=18/18.37921/-88.39860
http://www.openstreetmap.org/user/rcphillips/history#map=15/18.4050/-88.3770

**Comment by aawiseman** [comment] 2016-08-05 20:18
For example, the same user did all the buildings in this view, but Overpass Turbo only caught some. I wonder if that's related. http://overpass-turbo.eu/s/hHZ

**Comment by dalekunce** [comment] 2016-08-05 20:53
for sure related. If Overpass doesn't get the edit then it doesn't show up in the augmented diff which leads to it not showing up in the MM stats. This is the core of the problem that we have.

**Comment by kamicut** [comment] 2016-09-26 23:11
@aawiseman looking at that view more closely using OSM's query tool, it seems that Overpass Turbo did capture user "Lisette R-Z"'s building edits, the other user being `edtha`. Did the query change since you posted it in August? I'm trying to determine if Overpass back filled missing data at a later date or this was actually a case of Overpass not getting the data.

**Comment by aawiseman** [comment] 2016-10-11 18:58
@kamicut the query didn't change, maybe it back filled.

**Comment by kamicut** [comment] 2018-03-28 19:15
I think we can close this now, right @dalekunce @mojodna ?

**Closed** 2018-03-28 19:28 UTC
